version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "mambaforge-latest"
  jobs:
    post_checkout:
      - git fetch --unshallow || true
    pre_install:
      - git update-index --assume-unchanged .rtd-environment.yml docs/conf.py
    pre_build:
      # Note $DKIST_SAMPLE_DIR is set by RTD to ~/dkist_data
      - python -c "from dkist.data.sample import download_all_sample_data; download_all_sample_data()"
      - python -c "from dkist.data.sample import VISP_BKPLX; print(VISP_BKPLX)"

conda:
  environment: .rtd-environment.yml

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - htmlzip

python:
  install:
    - method: pip
      extra_requirements:
        - docs
      path: .
