version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-4.10"
  jobs:
    post_checkout:
      - git fetch --unshallow || true
    pre_install:
      - git update-index --assume-unchanged .rtd-environment.yml docs/conf.py
    pre_build:
      - pwd
      - echo $HOME
      - parfive https://dkist-data-us-east.s3.amazonaws.com/BKPLX_stokesI.tar https://dkist-data-us-east.s3.amazonaws.com/AJQWW_single_mosaic.tar
      - mkdir -p $HOME/dkist_data/BKPLX $HOME/dkist_data/AJQWW
      - tar -xv -f BKPLX_stokesI.tar --directory $HOME/dkist_data/BKPLX
      - tar -xv -f AJQWW_single_mosaic.tar --directory $HOME/dkist_data/AJQWW

conda:
  environment: .rtd-environment.yml

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - htmlzip

python:
  install:
    - method: pip
      extra_requirements:
        - docs
      path: .
