blank_issues_enabled: true
contact_links:
  - name: DKIST Community Chat
    url: https://openastronomy.element.io/#/room/#dki-solar-telescope:openastronomy.org
    about: A community support forum to help other community members.
