from ._attrs import (
    Dataset,
    WavelengthBand,
    Embargoed,
    Observable,
    Experiment,
    Proposal,
    TargetType,
    Recipe,
    FriedParameter,
    PolarimetricAccuracy,
    ExposureTime,
    EmbargoEndTime,
    BrowseMovie,
    BoundingBox,
    SpectralSampling,
    SpatialSampling,
    TemporalSampling,
)

# Trick the docs into thinking these attrs are defined in here.
for _a in (
    Dataset,
    WavelengthBand,
    Embargoed,
    Observable,
    Experiment,
    Proposal,
    TargetType,
    Recipe,
    FriedParameter,
    PolarimetricAccuracy,
    ExposureTime,
    EmbargoEndTime,
    BrowseMovie,
    BoundingBox,
    SpectralSampling,
    SpatialSampling,
    TemporalSampling,
):
    _a.__module__ = __name__

__all__ = [
    "Dataset",
    "WavelengthBand",
    "Embargoed",
    "Observable",
    "Experiment",
    "Proposal",
    "TargetType",
    "Recipe",
    "FriedParameter",
    "PolarimetricAccuracy",
    "ExposureTime",
    "EmbargoEndTime",
    "BrowseMovie",
    "BoundingBox",
    "SpectralSampling",
    "SpatialSampling",
    "TemporalSampling",
]
