name: Run benchmarks for main

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  schedule:
    #        ┌───────── minute (0 - 59)
    #        │ ┌───────── hour (0 - 23)
    #        │ │ ┌───────── day of the month (1 - 31)
    #        │ │ │ ┌───────── month (1 - 12 or JAN-DEC)
    #        │ │ │ │ ┌───────── day of the week (0 - 6 or SUN-SAT)
    - cron: '0 9 * * 1'  # Every Monday at 0900 UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  benchmarks:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@main
    container:
      volumes:
        - ~:/github
    with:
      default_python: '3.10'
      envs: |
        - linux: benchmark-main

  update-repo:
    runs-on: ubuntu-latest
    container:
      volumes:
        - ~:/github
    needs: [benchmarks]
    run: |
      git clone https://github.com/DKISTDC/dkist-benchmarks.git /github/dkist-benchmarks
      cd /dkist-benchmarks
      git add main.json
      git commit -m "Update benchmark data for main"
      git push origin main
