name: codspeed-benchmarks

on:
  push:
    branches:
      - "main"
    paths:
      - "dkist/**"
  pull_request:
    paths:
      - "dkist/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.14'
      - run: python -m pip install .[tests] pytest-codspeed
      - name: Run benchmarks
        uses: CodspeedHQ/action@281164b0f014a4e7badd2c02cecad9b595b70537 # v4.11.1
        with:
          mode: "instrumentation"
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: "pytest -vvv -r fEs --pyargs dkist --codspeed --remote-data=any"
