name: Publish Release

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

jobs:
  publish:
    # TODO: Ignore .dev tags
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@v1
    with:
      test_extras: tests
      test_command: pytest --pyargs dkist
    secrets:
      pypi_token: ${{ secrets.pypi_token }}
