name: Publish

on:
  - push
  - pull_request

defaults:
  runs-on: ubuntu-latest
  if: github.repository == 'DKISTDC/dkist'

env:
  # The name of the python package after install
  PACKAGE: 'dkist'

jobs:
  build-sdist:
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install python-build
        run: python -m pip install build

      - name: Build package
        run: python -m build --sdist .

      - name: Test package
        run: |
          cd ..
          python -m venv testenv
          testenv/bin/pip install pytest ${{ github.workspace }}/dist/*
          testenv/bin/pytest --pyargs $PACKAGE

  build-wheel:
    runs-on: ubuntu-latest
    if: github.repository == 'DKISTDC/dkist'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install python-build
        run: python -m pip install build

      - name: Build package
        run: python -m build --wheel .

      - name: Test package
        run: |
          cd ..
          python -m venv testenv
          testenv/bin/pip install pytest ${{ github.workspace }}/dist/*
          testenv/bin/pytest --pyargs $PACKAGE

  # publish:
  #     - name: Publish distribution 📦 to PyPI
  #       if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
  #       uses: pypa/gh-action-pypi-publish@master
  #       with:
  #         user: __token__
  #         password: ${{ secrets.pypi_password }}
